site_name: Hacking Documentation

site_url: https://chirag-bhil.github.io/site/

repo_url: https://github.com/chirag-bhil/site

theme:
  name: material
  palette:
    - scheme: slate
      primary: cyan
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - admonition
  - attr_list

extra_css:
  - stylesheets/extra.css

nav:
  - üè† Home: index.md
  
  - üòä Cybersecurity:
    - Web Hacking:
      - Overview: cybersecurity/web-hacking.md
      - SQL Injection: cybersecurity/sqli.md
      - OWASP Top 10: cybersecurity/owasp-top10.md
    
    - Bug Bounty:
      - 1. Intro:
        - 1. Web-Requests: cybersecurity/bug_bounty/1.web_requests.md
    
    - CTF Writeups:
      - TryHackMe:
        - Challenges:
          - Brains: cybersecurity/tryhackme/challenges/brains.md
      - Hack The Box: cybersecurity/hackthebox.md
      - General CTF: cybersecurity/ctf.md
    
    - Blogs: 
      - Trace Method: cybersecurity/extra/Trace_method.md
      - Comic Style Blog:
          - 1. Vector Cain Casefile: cybersecurity/extra/Vector_Cain_Casefile.md
  - üíª Programming:
    - Python:
      - Basics: programming/python-basics.md
      - Scripts: programming/python-scripts.md
    
    - C Programming:
      - Overview: programming/c.md
      - Pointers: programming/c-pointers.md
      - Data Structures: programming/c-ds.md
  
  - üìö Guides & Tutorials:
    - Linux: guides/linux.md
    - Tools: cybersecurity/tools/vim.md

